[package]
name = "rustdata-macros"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Procedural macros for rustdata-core: #[derive(Entity)], #[derive(QueryMethods)], #[derive(Projection)], #[derive(SqlType)]"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
darling = "0.23.0"
proc-macro2 = "1"
