//! # migration_test
//!
//! Demonstrates the rustdata migration + repository API.
//!
//! ## What a developer writes (the entire data layer):
//!
//!   1. SQL files in `migrations/`  — canonical dialect-agnostic SQL
//!   2. A struct with `#[derive(Entity, QueryMethods)]`
//!   3. `rustdata_migrations::migrate!(&pool).await?`
//!   4. `UserRepo::new(pool)` and the derived methods
//!
//! Everything else (transpilation, dialect detection, schema tracking,
//! SQL generation) is handled by the framework.

use rustdata_core::prelude::*;
use sqlx::sqlite::SqlitePoolOptions;
use uuid::Uuid;
use chrono::{DateTime, Utc};

// ── 1. Define your entity ────────────────────────────────────────────────────
//
// The derive macros generate:
//   • EntityDescriptor impl  — column metadata, bind/extract logic
//   • UserRepo type alias    — pinned to the Sqlite backend (from Cargo feature)
//   • find_by_* methods      — one per field, via QueryMethods

#[derive(Debug, Clone, Entity, QueryMethods)]
#[entity(table = "users", order_by = "created_at DESC")]
pub struct User {
    #[entity(id)]
    pub id: Uuid,
    pub username: String,
    pub email: String,
    pub created_at: DateTime<Utc>,
    pub active: bool,
    pub bio: Option<String>,
    pub is_premium: bool,
}

#[derive(Debug, Clone, Entity, QueryMethods)]
#[entity(table = "profiles", order_by = "created_at DESC")]
pub struct Profile {
    #[entity(id)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub display_name: String,
    pub avatar_url: Option<String>,
    pub created_at: DateTime<Utc>,
}

// ── 2. Bootstrap ─────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect("sqlite::memory:")
        .await?;

    // Apply all migrations in `migrations/` — one line, dialect inferred from pool type.
    // Transpilation, schema tracking, and ordered execution are fully automatic.
    rustdata_migrations::migrate!(&pool).await?;

    println!("✓ Migrations applied");

    // ── 3. Use the generated repositories ────────────────────────────────────

    let user_repo    = UserRepo::new(pool.clone());
    let profile_repo = ProfileRepo::new(pool.clone());

    // Insert a user
    let user = User {
        id:         Uuid::new_v4(),
        username:   "alice".into(),
        email:      "alice@example.com".into(),
        created_at: Utc::now(),
        active:     true,
        bio:        Some("rustdata enthusiast".into()),
        is_premium: false,
    };
    user_repo.insert(user.clone()).await?;
    println!("✓ Saved user:  {} ({})", user.username, user.id);

    // Insert a profile
    let profile = Profile {
        id:           Uuid::new_v4(),
        user_id:      user.id,
        display_name: "Alice A.".into(),
        avatar_url:   None,
        created_at:   Utc::now(),
    };
    profile_repo.insert(profile.clone()).await?;
    println!("✓ Saved profile: {}", profile.display_name);

    // Find by id
    let found = user_repo.find_by_id(user.id).await?;
    assert_eq!(found.as_ref().map(|u| &u.username), Some(&"alice".to_string()));
    println!("✓ find_by_id   → {:?}", found.as_ref().map(|u| &u.username));

    // Derived finder — find_by_active generated by #[derive(QueryMethods)]
    let active_users = user_repo.find_by_active(true).await?;
    println!("✓ find_by_active(true) → {} user(s)", active_users.len());
    assert!(!active_users.is_empty());

    // Derived finder — find_by_is_premium
    let premium = user_repo.find_by_is_premium(false).await?;
    println!("✓ find_by_is_premium(false) → {} user(s)", premium.len());

    // Update
    let mut updated = user.clone();
    updated.is_premium = true;
    user_repo.update(updated.clone()).await?;
    let reloaded = user_repo.find_by_id(user.id).await?.expect("must exist");
    assert!(reloaded.is_premium);
    println!("✓ Updated is_premium → {}", reloaded.is_premium);

    // Delete — profile first to satisfy the FK constraint on profiles.user_id
    profile_repo.delete(&profile.id).await?;
    user_repo.delete(&user.id).await?;
    let gone = user_repo.find_by_id(user.id).await?;
    assert!(gone.is_none());
    println!("✓ Deleted user — find_by_id returns None");

    println!("\n✅  All checks passed.");
    Ok(())
}