#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SqlTypeId {
    Uuid,
    Varchar,
    Text,
    BigInt,
    Int,
    SmallInt,
    Boolean,
    TimestampTz,
    Date,
    Decimal,
    Jsonb,
    Json,
    Bytes,
    Float,
    Custom(&'static str),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InsertStrategy {
    Provided,
    AutoGenerated,
    DefaultOnly,
    ServerTimestamp,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UpdateStrategy {
    Updatable,
    Immutable,
    Conditional,
    ServerTimestamp,
}

#[derive(Debug, Clone, Copy)]
pub struct ColumnDef {
    pub name: &'static str,
    pub sql_type: SqlTypeId,
    pub nullable: bool,
    pub is_id: bool,
    pub is_json: bool,
    pub insert_strategy: InsertStrategy,
    pub update_strategy: UpdateStrategy,
}

impl ColumnDef {
    pub const fn new(name: &'static str, sql_type: SqlTypeId) -> Self {
        Self {
            name,
            sql_type,
            nullable: false,
            is_id: false,
            is_json: false,
            insert_strategy: InsertStrategy::Provided,
            update_strategy: UpdateStrategy::Updatable,
        }
    }

    pub const fn id(mut self) -> Self {
        self.is_id = true;
        self.update_strategy = UpdateStrategy::Immutable;
        self
    }

    pub const fn nullable(mut self) -> Self {
        self.nullable = true;
        self
    }

    pub const fn json(mut self) -> Self {
        self.is_json = true;
        self
    }

    pub const fn insert(mut self, s: InsertStrategy) -> Self {
        self.insert_strategy = s;
        self
    }

    pub const fn update(mut self, s: UpdateStrategy) -> Self {
        self.update_strategy = s;
        self
    }

    pub fn is_inserted(&self) -> bool {
        matches!(
            self.insert_strategy,
            InsertStrategy::Provided | InsertStrategy::DefaultOnly
        )
    }

    pub fn is_updated(&self) -> bool {
        matches!(
            self.update_strategy,
            UpdateStrategy::Updatable | UpdateStrategy::Conditional
        )
    }
}

pub mod sql_gen {
    use super::*;
    use crate::dialect::SqlDialect;

    pub fn select_cols(columns: &[ColumnDef]) -> String {
        columns
            .iter()
            .map(|c| c.name)
            .collect::<Vec<_>>()
            .join(", ")
    }

    pub fn insert_cols(columns: &[ColumnDef]) -> String {
        columns
            .iter()
            .filter(|c| c.is_inserted())
            .map(|c| c.name)
            .collect::<Vec<_>>()
            .join(", ")
    }

    pub fn insert_param_count(columns: &[ColumnDef]) -> usize {
        columns.iter().filter(|c| c.is_inserted()).count()
    }

    pub fn update_set(columns: &[ColumnDef], dialect: SqlDialect) -> String {
        let mut idx = 1;
        columns
            .iter()
            .filter(|c| c.is_updated())
            .map(|c| {
                let ph = dialect.ph(idx);
                idx += 1;
                format!("{} = {}", c.name, ph)
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    pub fn update_param_count(columns: &[ColumnDef]) -> usize {
        columns.iter().filter(|c| c.is_updated()).count()
    }

    pub fn default_order_by(columns: &[ColumnDef]) -> String {
        columns
            .iter()
            .find(|c| c.is_id)
            .map(|c| format!("{} ASC", c.name))
            .unwrap_or_else(|| "1 ASC".to_string())
    }
}
