use crate::{
    entity::expand_derive, projection_derive::expand_projection, sql_type_derive::expand_sql_type,
};

fn parse_struct(input: proc_macro2::TokenStream) -> syn::DeriveInput {
    syn::parse2(input).unwrap()
}

// ─── Entity ─────────────────────────────────────────────────────

#[test]
fn entity_basic() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            email: String,
            name: String,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("EntityDescriptor for User"));
    assert!(output.contains(r#"const TABLE : & 'static str = "users""#));
    assert!(output.contains("type Id = uuid :: Uuid"));
    assert!(output.contains("pub type UserRepo = :: rustdata_core :: repo :: CrudRepository"));
}

#[test]
fn entity_with_soft_delete() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users", soft_delete = "deleted_at")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            deleted_at: Option<chrono::DateTime<chrono::Utc>>,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains(r#"SOFT_DELETE_COL : Option < & 'static str > = Some ("deleted_at")"#));
}

#[test]
fn entity_with_json_field() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            #[entity(json)]
            permissions: serde_json::Value,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("serde_json :: to_value"));
    assert!(output.contains("B :: bind_json_value"));
}

#[test]
fn entity_with_skip_field() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            #[entity(skip)]
            computed: String,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("computed : :: core :: default :: Default :: default ()"));
}

#[test]
fn entity_with_auto_generated() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            #[entity(auto_generated)]
            created_at: chrono::DateTime<chrono::Utc>,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("InsertStrategy :: AutoGenerated"));
    assert!(output.contains("UpdateStrategy :: Immutable"));
}

#[test]
fn entity_with_insert_only() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            #[entity(insert_only)]
            created_at: chrono::DateTime<chrono::Utc>,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("InsertStrategy :: Provided"));
    assert!(output.contains("UpdateStrategy :: Immutable"));
}

#[test]
fn entity_with_version() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            #[entity(version)]
            version: i64,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("UpdateStrategy :: Conditional"));
}

#[test]
fn entity_with_map() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            #[entity(map = "|v: String| v.to_uppercase()")]
            name: String,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("to_uppercase"));
}

#[test]
fn entity_with_custom_order_by() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users", order_by = "name ASC")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            name: String,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains(r#"const ORDER_BY : & 'static str = "name ASC""#));
}

#[test]
fn entity_with_column_override() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            #[entity(column = "email_address")]
            email: String,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains(r#""email_address""#));
}

#[test]
fn entity_with_option_field() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            middle_name: Option<String>,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains(". nullable ()"));
}

#[test]
fn entity_with_entity_type() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users", entity_type = "crate::domain::User")]
        struct UserRow {
            #[entity(id)]
            id: uuid::Uuid,
            email: String,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("type Entity = crate :: domain :: User"));
}

#[test]
fn entity_repo_type_alias() {
    let input = parse_struct(quote::quote! {
        #[entity(table = "users")]
        struct User {
            #[entity(id)]
            id: uuid::Uuid,
            email: String,
        }
    });
    let output = expand_derive(input).to_string();
    assert!(output.contains("pub type UserRepo = :: rustdata_core :: repo :: CrudRepository"));
    assert!(output.contains("CrudRepository < :: rustdata_core :: DefaultBackend , User"));
}

// ─── SqlType ─────────────────────────────────────────────────────

#[test]
fn sql_type_basic() {
    let input = parse_struct(quote::quote! {
        #[sql_type(delegate = "String")]
        struct Email(String);
    });
    let output = expand_sql_type(input).to_string();
    assert!(output.contains("impl :: rustdata_core :: sql_type :: SqlBind for Email"));
    assert!(output.contains("impl :: rustdata_core :: sql_type :: SqlExtract for Email"));
    assert!(output.contains("SqlBind for Option < Email >"));
    assert!(output.contains("SqlExtract for Option < Email >"));
    assert!(output.contains("& v . 0"));
}

#[test]
fn sql_type_with_uuid_delegate() {
    let input = parse_struct(quote::quote! {
        #[sql_type(delegate = "uuid::Uuid")]
        struct UserId(uuid::Uuid);
    });
    let output = expand_sql_type(input).to_string();
    assert!(output.contains("< uuid :: Uuid as"));
    assert!(output.contains("Ok (UserId ("));
}

// ─── Projection ─────────────────────────────────────────────────

#[test]
fn projection_basic() {
    let input = parse_struct(quote::quote! {
        struct UserName {
            id: uuid::Uuid,
            name: String,
        }
    });
    let output = expand_projection(input).to_string();
    assert!(output.contains("impl :: rustdata_core :: projection :: Projection for UserName"));
    assert!(output.contains("type Entity = UserName"));
    assert!(output.contains("ColumnDef :: new (\"id\" ,"));
    assert!(output.contains("ColumnDef :: new (\"name\" ,"));
}

#[test]
fn projection_with_multiple_types() {
    let input = parse_struct(quote::quote! {
        struct UserProfile {
            id: uuid::Uuid,
            email: String,
            age: i32,
            score: i64,
            active: bool,
            created_at: chrono::DateTime<chrono::Utc>,
        }
    });
    let output = expand_projection(input).to_string();
    assert!(output.contains("SqlTypeId :: Uuid"));
    assert!(output.contains("SqlTypeId :: Varchar"));
    assert!(output.contains("SqlTypeId :: Int"));
    assert!(output.contains("SqlTypeId :: BigInt"));
    assert!(output.contains("SqlTypeId :: Boolean"));
    assert!(output.contains("SqlTypeId :: TimestampTz"));
}
