[package]
name = "rustdata-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "chrono", "uuid"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = { version = "2" }
rustdata-macros = { path = "../rustdata-macros" }
sha2 = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
walkdir = { version = "2", optional = true }

[features]
default = ["postgres"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
mysql = ["sqlx/mysql"]
migration = ["dep:sha2", "dep:hex", "dep:walkdir"]
